<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INW-170" name="PchTestClass.FullRegtest" tests="11" failures="0" timestamp="08 May 2019 10:31:52 GMT" time="3.518" errors="1">
  <testcase name="AptTest" time="0.371" classname="PchTestClass.FullRegtest"/>
  <testcase name="SubmitbtnTest" time="0.280" classname="PchTestClass.FullRegtest"/>
  <testcase name="EmailTest" time="0.695" classname="PchTestClass.FullRegtest"/>
  <testcase name="CityTest" time="0.407" classname="PchTestClass.FullRegtest"/>
  <testcase name="FirstNameTest" time="0.227" classname="PchTestClass.FullRegtest"/>
  <testcase name="CnEmailTest" time="0.000" classname="PchTestClass.FullRegtest">
    <error type="org.testng.TestNGException" message="
Method public void PchTestClass.FullRegtest.CnEmailTest(java.lang.String) requires a @DataProvider named : getcnemail">
      <![CDATA[org.testng.TestNGException: 
Method public void PchTestClass.FullRegtest.CnEmailTest(java.lang.String) requires a @DataProvider named : getcnemail
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CnEmailTest -->
  <testcase name="LastNameTest" time="0.252" classname="PchTestClass.FullRegtest"/>
  <testcase name="ZipTest" time="0.274" classname="PchTestClass.FullRegtest"/>
  <testcase name="StateTest" time="0.300" classname="PchTestClass.FullRegtest"/>
  <testcase name="TitleTest" time="0.391" classname="PchTestClass.FullRegtest"/>
  <testcase name="AddTest" time="0.321" classname="PchTestClass.FullRegtest"/>
</testsuite> <!-- PchTestClass.FullRegtest -->
